CREATE TABLE users (
     id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     first_name VARCHAR(100) NOT NULL,
     last_name VARCHAR(100) NOT NULL,
     email VARCHAR(100) NOT NULL,
     password VARCHAR(100) NOT NULL,
     created_at DATETIME DEFAULT CURRENT_TIMESTAMP() NOT NULL,
     updated_at DATETIME DEFAULT CURRENT_TIMESTAMP() NOT NULL ON UPDATE CURRENT_TIMESTAMP(),
     delete_at DATETIME NULL
);

CREATE TABLE products (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    price DECIMAL(5, 2) NOT NULL,
    description varchar(255) NOT NULL,
    quantity INT NOT NULL ,
    image VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP() NOT NULL ON UPDATE CURRENT_TIMESTAMP(),
    deleted_at DATETIME NULL
);

CREATE TABLE orders (
      id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
      product_id INT UNSIGNED NOT NULL,
      product_name VARCHAR(100) NOT NULL,
      price DECIMAL(5, 2) NOT NULL,
      description varchar(255) NOT NULL,
      quantity INT NOT NULL ,
      image VARCHAR(100),
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP(),
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
      deleted_at DATETIME NULL
);

CREATE TABLE customerOrders (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    price DECIMAL(5, 2) NOT NULL,
    description VARCHAR(200) NOT NULL,
    image VARCHAR(100) NOT NULL,
    total_cost DECIMAL(5, 2) NOT NULL,
    quantity INTEGER (100) NOT NULL,
    customer_name VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    city VARCHAR(100) NOT NULL,
    address VARCHAR(400) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP() NOT NULL ON UPDATE CURRENT_TIMESTAMP(),
    delete_at DATETIME NULL
);


